# Generated by Django 3.2.9 on 2021-12-11 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Наименование продукта')),
                ('image', models.ImageField(blank=True, upload_to='products_images')),
                ('short_dec', models.CharField(blank=True, max_length=64, verbose_name='Краткое описание')),
                ('description', models.TextField(blank=True, verbose_name='Полное описание продукта')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Цена продукта')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Количство на складе')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.productcategory')),
            ],
        ),
    ]
