# Generated by Django 3.2.11 on 2022-01-17 13:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0005_auto_20220117_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 19, 13, 27, 35, 362033, tzinfo=utc), verbose_name='Истечение срока активации'),
        ),
    ]
