# Generated by Django 4.0 on 2022-01-17 13:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0006_alter_shopuser_activation_key_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 19, 13, 28, 56, 776237, tzinfo=utc), verbose_name='Истечение срока активации'),
        ),
    ]
