# Generated by Django 3.2.11 on 2022-01-18 09:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0011_alter_shopuser_activation_key_expires'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopuserprofile',
            name='domain',
            field=models.CharField(blank=True, max_length=256, verbose_name='ссылка на профиль'),
        ),
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 20, 9, 46, 48, 809841, tzinfo=utc), verbose_name='Истечение срока активации'),
        ),
    ]
