# Generated by Django 3.2.11 on 2022-01-18 09:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0012_auto_20220118_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopuserprofile',
            name='faw_music',
            field=models.CharField(blank=True, max_length=1000, verbose_name='любимая музыка'),
        ),
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 20, 9, 55, 25, 98813, tzinfo=utc), verbose_name='Истечение срока активации'),
        ),
    ]
