# Generated by Django 3.2.11 on 2022-01-22 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_alter_shopuser_age'),
        ('authapp', '0013_auto_20220118_1255'),
    ]

    operations = [
    ]
